import type { Theme } from '../../types/theme';

export const monokai: Theme = {
  id: 'monokai',
  name: 'Monokai',
  author: 'Wimer Hazenberg',
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: '#272822',
      elevated: '#1e1f1c',
      overlay: '#3e3d32',
      input: '#272822',
      tooltip: '#3e3d32',
    },
    surface: {
      primary: '#3e3d32',
      secondary: '#49483e',
      tertiary: '#575654',
      hover: '#49483e',
      active: '#66d9ef',
      disabled: '#3e3d32',
    },
    text: {
      primary: '#f8f8f2',
      secondary: '#a59f85',
      muted: '#908c78',
      disabled: '#49483e',
      accent: '#66d9ef',
      inverse: '#272822',
    },
    accent: {
      primary: '#66d9ef',
      secondary: '#ae81ff',
      success: '#a6e22e',
      warning: '#e6db74',
      error: '#f92672',
      info: '#66d9ef',
    },
    border: {
      subtle: '#3e3d32',
      default: '#49483e',
      strong: '#575654',
      focus: '#66d9ef',
    },
    semantic: {
      string: '#e6db74',
      number: '#ae81ff',
      boolean: '#ae81ff',
      date: '#a6e22e',
      null: '#75715e',
      primaryKey: '#fd971f',
      foreignKey: '#66d9ef',
      index: '#ae81ff',
      connectionActive: '#a6e22e',
      connectionInactive: '#75715e',
      modified: '#66d9ef',
      deleted: '#f92672',
      new: '#a6e22e',
    },
  },
  typography: {
    fontFamily: {
      base: 'Inter, system-ui, sans-serif',
      mono: 'Monaco, Consolas, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  layout: {
    borderRadius: {
      sm: '0.25rem',
      base: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      base: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  monacoTheme: {
    base: 'vs-dark',
    inherit: true,
    themeName: 'Monokai',
  },
};
