import type { Theme } from '../../types/theme';

export const nord: Theme = {
  id: 'nord',
  name: 'Nord',
  author: 'Arctic Ice Studio',
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: '#2e3440',
      elevated: '#3b4252',
      overlay: '#434c5e',
      input: '#2e3440',
      tooltip: '#434c5e',
    },
    surface: {
      primary: '#3b4252',
      secondary: '#434c5e',
      tertiary: '#4c566a',
      hover: '#434c5e',
      active: '#5e81ac',
      disabled: '#3b4252',
    },
    text: {
      primary: '#d8dee9',
      secondary: '#81a1c1',
      muted: '#6e94be',
      disabled: '#4c566a',
      accent: '#88c0d0',
      inverse: '#2e3440',
    },
    accent: {
      primary: '#88c0d0',
      secondary: '#b48ead',
      success: '#a3be8c',
      warning: '#ebcb8b',
      error: '#bf616a',
      info: '#81a1c1',
    },
    border: {
      subtle: '#3b4252',
      default: '#434c5e',
      strong: '#4c566a',
      focus: '#88c0d0',
    },
    semantic: {
      string: '#bf616a',
      number: '#b48ead',
      boolean: '#b48ead',
      date: '#a3be8c',
      null: '#4c566a',
      primaryKey: '#ebcb8b',
      foreignKey: '#88c0d0',
      index: '#b48ead',
      connectionActive: '#a3be8c',
      connectionInactive: '#4c566a',
      modified: '#88c0d0',
      deleted: '#bf616a',
      new: '#a3be8c',
    },
  },
  typography: {
    fontFamily: {
      base: 'Inter, system-ui, sans-serif',
      mono: 'Fira Code, Monaco, Consolas, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  layout: {
    borderRadius: {
      sm: '0.25rem',
      base: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      base: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  monacoTheme: {
    base: 'vs-dark',
    inherit: true,
    themeName: 'Nord',
  },
};
