import type { Theme } from '../../types/theme';

export const oneDarkPro: Theme = {
  id: 'one-dark-pro',
  name: 'One Dark Pro',
  author: 'BinaryFy',
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: '#282c34',
      elevated: '#21252b',
      overlay: '#2c313a',
      input: '#1e2227',
      tooltip: '#21252b',
    },
    surface: {
      primary: '#21252b',
      secondary: '#2c313a',
      tertiary: '#373d48',
      hover: '#2c313a',
      active: '#3e4451',
      disabled: '#21252b',
    },
    text: {
      primary: '#abb2bf',
      secondary: '#828997',
      muted: '#717d8c',
      disabled: '#4b5263',
      accent: '#61afef',
      inverse: '#282c34',
    },
    accent: {
      primary: '#61afef',
      secondary: '#c678dd',
      success: '#98c379',
      warning: '#e5c07b',
      error: '#e06c75',
      info: '#56b6c2',
    },
    border: {
      subtle: '#21252b',
      default: '#3e4451',
      strong: '#5c6370',
      focus: '#61afef',
    },
    semantic: {
      string: '#e06c75',
      number: '#d19a66',
      boolean: '#c678dd',
      date: '#98c379',
      null: '#5c6370',
      primaryKey: '#e5c07b',
      foreignKey: '#56b6c2',
      index: '#c678dd',
      connectionActive: '#98c379',
      connectionInactive: '#5c6370',
      modified: '#61afef',
      deleted: '#e06c75',
      new: '#98c379',
    },
  },
  typography: {
    fontFamily: {
      base: 'Inter, system-ui, sans-serif',
      mono: 'Fira Code, Monaco, Consolas, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  layout: {
    borderRadius: {
      sm: '0.25rem',
      base: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      base: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  monacoTheme: {
    base: 'vs-dark',
    inherit: true,
    themeName: 'One Dark Pro',
  },
};
