export interface Product {
  id: string;
  name: string;
  logo: string;
  width: number;
  height: number;
  tagline: string;
  features: Record<string, string>;
}

export const FEATURE_LABELS: { key: string; label: string }[] = [
  { key: "license", label: "License" },
  { key: "pricing", label: "Pricing" },
  { key: "notebooks", label: "SQL notebooks" },
  { key: "plugins", label: "Plugin system" },
  { key: "mcp", label: "MCP / AI integration" },
  { key: "editor", label: "Editor" },
  { key: "ssh", label: "SSH tunneling" },
  { key: "databases", label: "Databases" },
  { key: "platforms", label: "Platforms" },
];

export const products: Product[] = [
  {
    id: "tabularis",
    name: "Tabularis",
    logo: "/img/logo.png",
    width: 120,
    height: 120,
    tagline: "Open-source SQL workspace with notebooks, plugins, and MCP.",
    features: {
      license: "Open-source",
      pricing: "Free",
      notebooks: "✅ Native",
      plugins: "✅ Modern, JSON-RPC drivers",
      mcp: "✅ Built-in",
      editor: "Monaco-based",
      ssh: "✅ Keychain-backed",
      databases: "PostgreSQL, MySQL/MariaDB, SQLite (+ plugins)",
      platforms: "macOS · Linux · Windows (Tauri)",
    },
  },
  {
    id: "dbeaver",
    name: "DBeaver",
    logo: "/img/logos/dbeaver.png",
    width: 128,
    height: 128,
    tagline: "Mature Eclipse-based database tool with broad JDBC coverage.",
    features: {
      license: "Open-source (Apache 2.0) / Paid PRO",
      pricing: "Free (CE) · Paid (PRO, Enterprise)",
      notebooks: "❌",
      plugins: "✅ Eclipse-based",
      mcp: "❌",
      editor: "Eclipse text editor",
      ssh: "✅",
      databases: "80+ via JDBC",
      platforms: "macOS · Linux · Windows (Eclipse RCP)",
    },
  },
  {
    id: "tableplus",
    name: "TablePlus",
    logo: "/img/logos/tableplus.png",
    width: 192,
    height: 192,
    tagline: "Polished proprietary desktop client with native feel.",
    features: {
      license: "Proprietary",
      pricing: "Freemium · Paid license",
      notebooks: "❌",
      plugins: "❌",
      mcp: "❌",
      editor: "Custom native",
      ssh: "✅",
      databases: "~20 backends",
      platforms: "macOS · Linux · Windows · iOS",
    },
  },
  {
    id: "datagrip",
    name: "DataGrip",
    logo: "/img/logos/datagrip.svg",
    width: 100,
    height: 100,
    tagline: "JetBrains IDE-style database tool with marketplace plugins.",
    features: {
      license: "Proprietary (JetBrains)",
      pricing: "Paid (subscription)",
      notebooks: "❌",
      plugins: "✅ JetBrains marketplace",
      mcp: "❌",
      editor: "IntelliJ editor",
      ssh: "✅",
      databases: "Many via JDBC",
      platforms: "macOS · Linux · Windows (JVM)",
    },
  },
  {
    id: "beekeeper",
    name: "Beekeeper Studio",
    logo: "/img/logos/beekeeper.svg",
    width: 100,
    height: 100,
    tagline: "Open-core Electron client with a clean SQL editor.",
    features: {
      license: "Open-source (GPLv3) / Paid Ultimate",
      pricing: "Free (Community) · Paid (Ultimate)",
      notebooks: "❌",
      plugins: "Limited",
      mcp: "❌",
      editor: "CodeMirror",
      ssh: "✅",
      databases: "PG, MySQL, SQLite, SQL Server, MariaDB, others",
      platforms: "macOS · Linux · Windows (Electron)",
    },
  },
  {
    id: "dbgate",
    name: "DbGate",
    logo: "/img/logos/dbgate.svg",
    width: 100,
    height: 100,
    tagline: "Cross-platform tool with SQL and NoSQL support.",
    features: {
      license: "Open-source (MIT) / Paid Premium",
      pricing: "Free (CE) · Paid (Premium)",
      notebooks: "Limited",
      plugins: "✅",
      mcp: "❌",
      editor: "Monaco-based",
      ssh: "✅",
      databases: "PG, MySQL, SQLite, MS SQL, MongoDB",
      platforms: "macOS · Linux · Windows · web (Electron)",
    },
  },
  {
    id: "navicat",
    name: "Navicat",
    logo: "/img/logos/navicat.png",
    width: 312,
    height: 80,
    tagline: "Commercial multi-database admin tool with broad coverage.",
    features: {
      license: "Proprietary",
      pricing: "Paid (per-seat license)",
      notebooks: "❌",
      plugins: "❌",
      mcp: "❌",
      editor: "Custom native",
      ssh: "✅",
      databases: "Many (incl. Oracle, SQL Server)",
      platforms: "macOS · Linux · Windows · iOS",
    },
  },
  {
    id: "pgadmin",
    name: "pgAdmin",
    logo: "/img/logos/pgadmin.png",
    width: 920,
    height: 920,
    tagline: "Official PostgreSQL admin UI, web-based.",
    features: {
      license: "Open-source (PostgreSQL License)",
      pricing: "Free",
      notebooks: "❌",
      plugins: "Limited",
      mcp: "❌",
      editor: "CodeMirror (web)",
      ssh: "✅",
      databases: "PostgreSQL only",
      platforms: "macOS · Linux · Windows · web",
    },
  },
  {
    id: "phpmyadmin",
    name: "phpMyAdmin",
    logo: "/img/logos/phpmyadmin.png",
    width: 172,
    height: 101,
    tagline: "Classic web-based MySQL/MariaDB admin panel.",
    features: {
      license: "Open-source (GPLv2)",
      pricing: "Free",
      notebooks: "❌",
      plugins: "Limited",
      mcp: "❌",
      editor: "Basic textarea",
      ssh: "Via reverse tunnel only",
      databases: "MySQL, MariaDB",
      platforms: "Any browser",
    },
  },
  {
    id: "heidisql",
    name: "HeidiSQL",
    logo: "/img/logos/heidisql.png",
    width: 780,
    height: 198,
    tagline: "Lightweight free Windows-native MySQL/MariaDB tool.",
    features: {
      license: "Open-source (GPLv2)",
      pricing: "Free",
      notebooks: "❌",
      plugins: "Limited",
      mcp: "❌",
      editor: "Custom (Scintilla)",
      ssh: "✅",
      databases: "MySQL, MariaDB, PostgreSQL, SQL Server, SQLite",
      platforms: "Windows native · Wine elsewhere",
    },
  },
];

export function getProduct(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}
