/**
 * App version used throughout the website.
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated by scripts/sync-version.js
 * To update, run: pnpm version <new-version> && pnpm sync-version
 */
export const APP_VERSION = "0.9.12";
